- name: Wait for Jenkins to be up
  wait_for:
    host: "{{ ansible_host }}"
    port: "{{ jenkins_http_port | default('8080') }}"
    timeout: 120

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
  loop: "{{ lookup('file', 'roles/jenkins_pluging/files/jenkins_plugins.txt').splitlines() }}"
  notify:
    - Restart Jenkins

